### ISSUE TITLE
Some changes in change log 1.0.2 to 1.0.3 are missing

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [BrickSchema/Brick#123]
Dear BRICK team,

I was migrating some components of the [MOEEBIUS ontology](https://github.com/MOEEBIUS/MOEEBIUS_Ontology/blob/master/MOEEBIUSOntology/MOEEBIUS-0.0.4.ttl) to BRICK v1.0.3. Thanks for providing the change log as of https://github.com/BrickSchema/Brick/pull/42.

Besides the mentioned changes I observed also some additional changes on some object properties, e.g.:

```turtle

@prefix bf2: <https://brickschema.org/schema/1.0.2/BrickFrame#> .
@prefix bf3: <https://brickschema.org/schema/1.0.3/BrickFrame#> .

bf3:feeds a owl:ObjectProperty ;
    owl:inverseOf bf3:isFedBy .

# vs.

bf2:feeds a owl:ObjectProperty ;
	owl:inverseOf bf2:isFedBy ;
	a owl:AsymmetricProperty , owl:IrreflexiveProperty .
```

Potentially the changes (removal of assymmetric etc.) can be added to the documentation.

Best

Georg

**Comment by gtfierro** [comment]
Hi Georg:

Thanks for catching this! We recommend using Brick v1.1 for all migrations and integration. The ad-hoc nature of the 1.0.2 and 1.0.3 editions made them hard to maintain and debug (and thus provide more robust changelogs). Since v1.1 the changelogs should be much more complete and maintained going forward. There's additionally a [conversion tool](https://github.com/BrickSchema/Brick/tree/master/tools/convert) for migrating models against Brick v1.0.2 and v1.0.3 to v1.1. Can you give v1.1 a try and let me know how it works? It should maintain some of these object properties as well

**Comment by gtfierro** [comment]
Closing for now, but please let me know if there's any followup we can do for Brick v1.1

**Comment by GeorgFerdinandSchneider** [comment]
Apologies for the delayed response. I will look into v1.1 and get back to you. Fine to close the issue. Best,
