### ISSUE TITLE
Highest/Warmest Equivalent Classes

### ISSUE THREAD

**Issue by JoelBender** [BrickSchema/Brick#129]
The `Highest_Zone_Air_Temperature_Sensor` has an OWL equivalent class relationship with  `Warmest_Zone_Air_Temperature_Sensor` yet the former has `tag:Highest` and latter has `tag:Warmest`.  As long as a thing has both tags then I would expect it to be an instance of both types, but if it's a "highest" that does not have a "warmest" tag does the inference engine assume that (thanks to open world) that somewhere in the universe that there must be a "warmest"?

What is the intent of have two classes, is it simply the idea that someone can use "highest" or "warmest" and they are they mean the same thing?

**Comment by gtfierro** [comment]
This is one of those classes on our list of "these sound the same but they came from different buildings and we're not exactly sure whether or not they refer to the same concept" :)

We're unfortunately now at the stage where the Brick documentation appears higher on Google search results than some source material, but my guess is that `Highest_Zone_Air_Temperature_Sensor`  and `Warmest_Zone_Air_Temperature_Sensor` are computed values stored in the BMS in conjunction with `Lowest_`/`Coolest_`/`Average_` variants. Is that your experience?

If that's the case then we might want to drop the alternatively-phrased "flavors" that ultimately mean the same thing (e.g. drop `Warmest_` for `Highest_` or vice versa). Currently the inference engine will add the `warmest` tag if you are an instance of `Highest_Zone_Air_Temperature_Sensor` (class -> tag inference), but because we are not using OWL inference for tag -> class, you only need the tags for one of the equivalent classes in order to produce the correct inference.

**Comment by gtfierro** [comment]
@JoelBender what do you think of replacing `Highest` with `Warmest` and `Lowest` with `Coolest` where the points pertain to temperature? I'm thinking we might remove the `Highest`/`Lowest` variants altogether, or at least mark them as deprecated to indicate that users should use the other point.

**Comment by praftery** [comment]
Yes, I believe these both refer to the same thing and were simply described differently by the controls contractor on the respective sites: The zone temperature that is highest/warmest and thus driving the temperature of the cold air from the air handling unit down to it's current point.

I agree that it's clearer (to me anyway!) to change to 'standardize' to Warmest/Coolest.

**Comment by gtfierro** [comment]
Thanks @praftery !

Changes captured in PR https://github.com/BrickSchema/Brick/pull/133. I'll do a quick look for similar redundancies/confusions that can be rectified in the same PR

**Comment by gtfierro** [comment]
Fixed in https://github.com/BrickSchema/Brick/pull/133
