### ISSUE TITLE
Resolve On/Off, Start/Stop points

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#130]
Is there a significant semantic difference between them? If so, what is it? If not, can we combine these two families of points into a single one that is easier to use and make sense of?

**Comment by fstinner** [comment]
Start/Stop can also be the start and stop of a control sequence. It depends on the context. On/Off is not as specific as Start/Stop, although both are often used in the same semantic way. 

In short: related, but not the same

**Comment by JoelBender** [comment]
Other old school terms are Trip/Close referring to the relay connected to some operating equipment like fans and pumps.  This is why BACnet uses specific enumerations active and inactive for Binary Input/Output/Value objects because True/False is also related, but not the same.

**Comment by gtfierro** [comment]
To help resolve this I'm drafting some documentation for start/stop vs on/off and also command vs status. Let me know what you think:

- `brick:Command`: A Command is a control point offering read/write functionality that directly affect the state of equipment
- (subclass of Command) `brick:On_Off_Command`: An On/Off Command controls or reports the binary status of a control loop, relay or equipment activity
- (subclass of On Off Command) `brick:Off_Command`: An Off Command controls or reports the binary 'off' status of a control loop, relay or equipment activity. It can only be used to stop/terminate/deactivate an associated equipment or process, or determine that the related entity is 'off'
- similar story for `On_Command`
- (subclass of On Off Command) `brick:Start_Stop_Command`: A Start/Stop Command controls or reports the active/inactive status of a control sequence

The `Status` variants of this are "read-only".

Does this match your understanding/expectation?

**Comment by praftery** [comment]
I understand the semantic difference between start/stop and on/off is the distinction between representing a command or instruction to do something (start the motor) or reporting the state of something (the motor is on). In terms of what the controller sees, that's a binary output (e.g. energize a relay controlling a fan motor) or a binary input (measure whether a contact is open or closed). Often On/Off could be either a command (a binary output) or a state measurement (binary input), but I think Start/Stop is rarely used when it is a measurement.

I think Gabe's proposed documentation resolves this. The only grey area is as Joel notes - values of True/False can correspond to the equipment being On/Off _or vice versa_ depending on the equipment - if it is normally open or normally closed. If reversed, then the bacnet Polarity property indicates this. I think the timeseries we work with should be stored with that inversion already handled such that a value of true always represents on/start. Maybe add some clarification to the docs to that effect?

**Comment by weyvogel** [comment]
Hi Gabe, here's Mingjun. I've discuessed this topic with my colleagues and found some intresting tings under Brick ontology catergories. The Start_Stop_Command is subClassOf On_Off_Command but the On_Off_Status and Start_Stop_Status are on the same level. I have considered the difference between Command and Status. Here's my opinion(see the pic)
![Command-Status](https://user-images.githubusercontent.com/37796204/80202151-7f8bc600-8625-11ea-8377-5939e78b747a.png)

A command is the wish of the operating status of a device, the chiller receives a Start_Command and normally would then be turned on. But if the chiller is defected, the Command would be True but actually the chiller doesn't run.  The Status shows actually if the Chiller runs or not, that means the Status should be False if the chiller's defected. In this case I thought the Start_Stop_Command is subClassOf On_Off_Command mankes sense.
I'm still not that clear with the difference between Start_Stop_Status and On_Off_Status, I could only understand in this way: in order to turn off a motor, there's a specific sequece to achieve.  E.g. the gasoline could be firstly cut down, the engine oil keeps lubricating the system till the piston stop, the cooling system keeps working till the temperature's in order and so on. This process refers to a Stop_Status, while a Off_Status describes the status after it‘s completely shut down. Does that make any sense?

**Comment by gtfierro** [comment]
@weyvogel I think your characterizations of Command (desired status) vs Status (reported status) is a good one.

Regarding `Start_Stop_Status` vs `On_Off_Status`: I think `On_Off_Status` makes sense to use to describe the current binary status of a control loop, relay or equpment activity (this is the analogous definition to the generic `On_Off_Command` definition I gave above). A `Start_Stop_Status` is a subclass of `On_Off_Status` that is used specifically to describe the binary active/inactive status of control loops but not equipment activities or relays.

For your example with a motor, you would use `On_Off_Status` to report whether or not the motor is on. `Start_Stop_Status` wouldn't be used because the motor status is not a control loop.

Maybe one distinction is `Start_Stop` is logical where `On_Off` is both logical and physical?

---

The case where `Start_Stop` is a subclass of `On_Off` in the `Command` hierarchy for not the `Status` hierarchy is an oversight and is fixed in the pending PR https://github.com/BrickSchema/Brick/pull/132. This is easy enough to swap in case we decide that they really should be separate for `Status`, but I think it makes sense to have consistent structures.

**Comment by gtfierro** [comment]
@praftery capturing NC vs NO for what "on" or "off" means is definitely important. I'll have to give more thought as to how we want to address that specifically; it might be an attribute of equipment or point classes?

**Comment by gtfierro** [comment]
Resolving the discussion with the definitions we mentioned: https://github.com/BrickSchema/Brick/pull/132
