### ISSUE TITLE
Simplifying Parameter/Limit with Point-to-point relationships

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#142]
This thought occurred to me when I was beginning to fill out the definitions for `Limit` parameters. A `Limit` is a parameter that places an upper or lower bound on the range of permitted values of another point. You can see from the list below that there are a large number of `Limit` points that all have very similar names to the `Setpoint` points that they are about.

```
    Air_Flow_Setpoint_Limit
    Max_Air_Flow_Setpoint_Limit
    Max_Cooling_Discharge_Air_Flow_Setpoint_Limit
    Max_Occupied_Cooling_Discharge_Air_Flow_Setpoint_Limit
    Max_Unoccupied_Cooling_Discharge_Air_Flow_Setpoint_Limit
    Max_Cooling_Supply_Air_Flow_Setpoint_Limit
    Max_Occupied_Cooling_Supply_Air_Flow_Setpoint_Limit
    Max_Unoccupied_Cooling_Supply_Air_Flow_Setpoint_Limit
    Max_Heating_Discharge_Air_Flow_Setpoint_Limit
    Max_Occupied_Heating_Discharge_Air_Flow_Setpoint_Limit
    Max_Unoccupied_Heating_Discharge_Air_Flow_Setpoint_Limit
    Max_Heating_Supply_Air_Flow_Setpoint_Limit
    Max_Occupied_Heating_Supply_Air_Flow_Setpoint_Limit
    Max_Unoccupied_Heating_Supply_Air_Flow_Setpoint_Limit
    Min_Air_Flow_Setpoint_Limit
```

Having two lists of points with $3n$ classes ($n$ setpoint classes, $2n$ limit classes for max and min bounds) can be tricky to maintain: the set of classes must remain in sync in terms of their definitions to make sure that all setpoints have corresponding limits. It's also a good deal of classes that one has to wade through in the documentation.

An alternative approach here would be to introduce properties that describe the relationship between points. Imagine a property called `boundsValueOf` (or something similar) that would describe the relationship between `Limit` points and `Setpoint` points:

```turtle
    brick:boundsValueOf a owl:ObjectProperty;
        rdfs:domain brick:Limit,
        rdfs:range brick:Setpoint .

    brick:Limit a owl:Class ;
        rdfs:subClassOf brick:Point .
    brick:Max_Limit a owl:Class ;
        rdfs:subClassOf brick:Max_Limit ;
        skos:definition "Places an upper limit on the permitted range of values for another point" .
    brick:Min_Limit a owl:Class ;
        rdfs:subClassOf brick:Min_Limit ;
        skos:definition "Places an lower limit on the permitted range of values for another point" .
        
    :my_air_flow_setpoint   a   brick:Air_Flow_Setpoint .

    :mafs_upper_limit a brick:Max_Limit ;
        brick:boundsValueOf :my_air_flow_setpoint .
    :mafs_lower_limit a brick:Min_Limit ;
        brick:boundsValueOf :my_air_flow_setpoint .
```

This would allow a small number of `Limit` classes to cover all of the potential use cases of `Max_*` and `Min_*` point classes. We can use this same approach to describe relationships between setpoints and sensors/commands too, for example.

Thoughts?

@jbkoh 

@JoelBender : this is similar to what the REC folks said on the last call about doing some of the typing in A-Box rather than T-Box. I'm thinking about adopting that approach for handling some of the eventual parameterization of equipment definitions: e.g. for capturing the type of a heat exchanger, capabilities of a VAV, and so on

**Comment by JoelBender** [comment]
For our local vernacular, there are no limits on setpoints but there are limits defined for acceptable values of observed properties.  For example, if some "supply air" is the feature of interest and "supply air flow" is the observable property, then the "supply air flow sensor" is perhaps a BACnet Analog Input Object that provides the current value when it is read.  That same object also provides High_Limit and Low_Limit and Deadband properties, which are referred to as "supply air flow high limit", etc.

Maybe these refer to local temperature adjustment requests, like "my office is a little too warm for me right now so I would like the setpoint to be a few degrees colder" and there are limits (like +/-5 degrees) that I'm allow to adjust it, but those would be limits on the space/zone temperature setpoint that would not apply to the supply air temperature.  There aren't any event or fault algorithms that I know that put limits on setpoints, and if there were they would have to be qualified as being a high limit or low limit.  If there is an Analog Value Object which is being used as a setpoint it could have High_Limit and Low_Limit properties, so I guess "supply air flow setpoint high limit" is possible.  In BACnet a setpoint is a property of a Loop Object.

You are correct with the A-Box/T-Box distinction, you are basically treating the setpoint (or more generically anything that has value) as a property that can have other properties, so you don't describe them in the class name, you make them additional things you can add to lots of stuff.

Here's a crack at it, and this may be wrong.

Let Level-0 be "thing p-0 value-0" and Level-1 be "thing has-property [ a p-1; has-value value-1]" and Level-2 becomes "thing has-property [a p-1; has-other-property [a p-2; has-value value-2]".  I've seen presentations where this is used during the evolution of a model, so there might be more than one instance of a relationship from a thing to a p-1 property that has version/source information (second iteration of the design phase of the door to this room as provided by the customer, which is of course not what is installed).  The general consensus seems to be that Level-2 make queries unnecessarily complicated for most situations and Level-1 is fine, so "thing has-property [a  p-1; has-value value-1; has-other-property value-2 ]" is good enough.

We also say "supply air flow high limit" rather than "max supply air flow" because we tack "alarm" on the end to specify the condition "supply air flow high limit alarm" and it fits with a hierarchy of names that begin with the facility, "BartonHall.AC-1.SupplyAir.Flow.HighLimit.Alarm".

We have not attempted to distinguish between the capabilities of a piece of equipment, a.k.a., name plate properties, vs the acceptable values for an installation.  There is a IFC4 based [PROPS Ontology](https://github.com/w3c-lbd-cg/lbd/blob/gh-pages/presentations/props/presentation_LBDcall_20180312_final.pdf) in the W3C LBD Community Group that goes into these topics because it shows up during design and construction.

**Comment by gtfierro** [comment]
My understanding of the "limit" point labels that we've mined out of existing buildings is that they fall mostly into the camp of high/low limits on the permitted values of setpoints. It seems that Alarms and Limits have somewhat of a parallel structure in that their values are associated with the values of other Points: Limits are associated with the values of Setpoints and Alarms are associated with the values of Sensors (as one example).

I think the Level-1 approach works for us here as well, and it has the advantage of aligning with the semantic model that already exists within Brick: just as Points describe properties of equipment and substances over time, they can also describe properties of other Points over time. Version/source information can always be carried forward as reified metadata, so I'm not too concerned with incorporating those annotations directly e.g. as the Level-2 structure suggests.

I'll have to admit that the slides in the PROPS ontology are hard for me to decipher. From how you described it, is the essential question how to distinguish between the properties that are fundamental to the "type" of a thing vs the the properties/values that it happens to have?

**Comment by gtfierro** [comment]
Closing for now
