### ISSUE TITLE
Container Classes for Grouping Entities

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#233]
There has been some call from the community to provide classes that define collections of other Brick entities:
- *Location Portfolio* or *Project* for a collection of Sites
- *System* for a group of Equipment + Points assembled for a particular set of use cases
- *Loop* for a discrete group of Equipment + Points through which a substance flows (a Loop may be a part of a System?)

List others! We should be able to include some of these in a future 1.2.x release

**Comment by epaulson** [comment]
Just to come back to 'Location Portfolio', Portfolio seems to be the term of the art as one of the top level containers for buildings or site. CRE firms talk about their 'portfolios' of buildings and there's the Energy Star Portfolio Manager which you can "Use [PM] to benchmark the performance of one building or a whole portfolio of buildings, all in a secure online environment." 

(Unfortunately, PortfolioManager has a portfolio of properties in their UI rather than a portfolio of buildings, which isn't going to make life less confusing for graph database users)

So you do wind up seeing 'portfolio' as the top-level data structure in the UIs of these sorts packages - if you collapse all navigation trees you'll see only the portfolios on left sidebars. For analytics, we'll also want to be able to exchange "portfolios" of buildings to do benchmarking against other portfolios.

I don't think "project" is the right term for this.

**Comment by david-waterworth** [comment]
A couple of other collections I've come across recently are AHU's and FCU's. Each floor of a building has a number of AHU's and FCU's, each of which has it's own BACnet controller. There's also a controller responsible for the overall coordination of all the floor AHU's and another for all the FCU's. Each has its own set of points which are shared with the AHU's / FCU's which are being controlled - points such as average floor temperature etc.

I'm not 100% sure but I suspect it's easier to program a BACnet system where shared points are written/read to/from a single central device (hub / spoke model) rather than each controller having to read from all their peers.

I'm not 100% sure that this is necessary for a Brick model, in our proprietary schema we did create a "Common AHU" and "Common FCU" class which is referred to by all the AHU's / FCU's which share points between the floor controllers. You could probably just model the points as sensors etc located on Floor X and not associated them with a specific controller but I thought I'd raise it anyway.

**Comment by gtfierro** [comment]
Please see https://github.com/BrickSchema/Brick/pull/269 for the collection types implementation

I think in the future we may explore collections which involve controllers, etc but I would like to postpone that until we have a better treatment of BMS concepts

**Comment by david-waterworth** [comment]
That makes sense. BTW here are some examples:

> L07_Zone3_AHrs
> L07_Zone3_AHrsRunEn
> L07_Zone3_AHrsRunPeriod
> L07_Zone3_AHrsRunTime
> L07_Zone3_AHrsTP
> L07_Zone3_AvgRmTemp
> L07_Zone3_En

Some of these make sense as sensor points in Zone3 of Level07 (i.e. maybe AvgRmTemp). But it seems odd to have a Run Enable Command as a Zone point so this is where some sort of Zone Controller concept may be required at some stage (there's a series of these points, L07_AHU_* and Lo7_VAV_* etc.)
