### ISSUE TITLE
When using the BRICK RDF namespace ensure existence

### ISSUE THREAD

**Issue by iamliamc** [BrickSchema/Brick#249]
What's the deal here? 

Essentially there is no "enforcement" that anything used in the `brick` namespace actually exists in the namespace...? 

Am I missing something obvious? 
```
BRICK = Namespace("https://brickschema.org/schema/Brick#")
BRICK.Variable_Air_Volume_Box
rdflib.term.URIRef('https://brickschema.org/schema/Brick#Variable_Air_Volume_Box')
BRICK.Variable_Air_Volume_BLAH
rdflib.term.URIRef('https://brickschema.org/schema/Brick#Variable_Air_Volume_BLAH')
```

https://github.com/BrickSchema/Brick/blob/master/examples/example1/generate.py#L92

**Comment by gtfierro** [comment]
No, you're not missing anything --- this is just how RDFlib behaves. This was a bit of a head-scratcher when we first started RDFlib, but the intent is to (a) prevent dependency loops (if I can't refer to `BRICK.VAV_BLAH` then how could I ever define it?) and (b) to stay in line with the open-world assumption (essentially, just because `BRICK.VAV_BLAH` doesn't exist in Brick.ttl doesn't mean it doesn't exist elsewhere).

Is your intent to ensure that the classes you are using are actually defined in Brick.ttl? It may be worth it for us to develop a SHACL shape that addresses this. In general, it is the role of validators/linters to perform that kind of task

**Comment by iamliamc** [comment]
Good deal thanks for taking that question here where... i knew it wasn't well all that related to this repo.
