### ISSUE TITLE
Adding dual duct AHU and hot and cold deck equipments

### ISSUE THREAD

**Issue by lazlop** [BrickSchema/Brick#376]
I need to model a dual duct AHU system. Currently, I'm thinking the best way to do this would be to have 3 pieces of equipment. A dual duct AHU, a hot deck, and a cold deck. The dual duct AHU will contain the hot and cold decks, and the hot and cold decks will  feed other pieces of equipment. The diagram below shows something like this. Can I add this to the brick schema?
![image](https://user-images.githubusercontent.com/69093818/156326661-bdffe236-2a68-4219-8c88-2d14cc154f3d.png)

**Comment by gtfierro** [comment]
Hi @lazlop! Thanks for filing the issue. Can you put together a PR implementing what you have in mind? We can discuss it at one of the upcoming Brick ontology working group meetings (https://brickschema.org/blog/working-groups/). I could see hot/cold deck as being "equipment", perhaps; or we can create a dual-duct AHU but otherwise simplify the rest of the topological model; or perhaps another approach altogether. Looking forward to what you have in mind!
