### ISSUE TITLE
Add parent property of Brick's inter-node properties

### ISSUE THREAD

**Issue by danjhugo** [BrickSchema/Brick#415]
Proposal: brick's inter-node properties to be defined as "`rdfs:subPropertyOf brick:interNodeProperty`", or similar. 

Explanation... 

Recently, I was composing a query that, among other things, needed to find instance nodes adjacent to a target node and the relationship between them (`?target ?rel ?other`), applying a constraint to drop matches where the object is something other than another brick instance node. While I could easily add the constraint "`?other rdf:type/rdfs:subClassOf* brick:Class`", property path quantifiers can be expensive (total query times in Blazegraph was in the order of 250-300ms which is excessive). 

I got this down to about 100ms by instead defining a parent class for Brick's inter-node properties and constraining for "`?rel rdfs:subPropertyOf brick:interNodeProperty`" in my query. (I also get the same times with "`FILTER( ?linkOut = brick:hasPart || ?linkOut = brick:isPartOf` ... etc", but that just looks clumsy). 

I know this is a bit of a corner case and doesn't change semantics, but it might be useful to include for the sake of query simplicity & performance? 

```
brick:interNodeProperty a owl:ObjectProperty ; skos:definition "Abstract superproperty for properties that relate two instance nodes".
brick:hasPart       rdfs:subPropertyOf brick:interNodeProperty .
brick:isPartOf      rdfs:subPropertyOf brick:interNodeProperty .
brick:feeds         rdfs:subPropertyOf brick:interNodeProperty .
brick:feedsAir      rdfs:subPropertyOf brick:interNodeProperty .
brick:isFedBy       rdfs:subPropertyOf brick:interNodeProperty .
brick:hasPoint      rdfs:subPropertyOf brick:interNodeProperty .
brick:isPointOf     rdfs:subPropertyOf brick:interNodeProperty .
brick:hasLocation   rdfs:subPropertyOf brick:interNodeProperty .
brick:isLocationOf  rdfs:subPropertyOf brick:interNodeProperty .
```

**Comment by gtfierro** [comment]
It may be a good idea to add a superproperty for all/most of the Brick relationships (like we do for the classes), and since that is an isomorphic change I think this is something we can add in 1.3.1. I'm on board mostly for the modeling consistency --- I'm not really in favor of an ontological change purely for a performance improvement. Adding a set of `FILTER` clauses doesn't feel that clunky in my opinion, and is certainly less complex than many business-logic oriented queries (page long SQL queries, etc) --- if you are encoding this into a tool, then the complexity/clunkiness of the query doesn't really matter as much either because it is hidden.

You can also use CONSTRUCT queries to "cache" the kind of information you are looking for as part of a preprocessing step.

In any case, I think we can add a `brick:Relationship` as a superproperty of existing Brick relationships in a future version.
