### ISSUE TITLE
Use of bsh:RDFSSubPropertyOfRule

### ISSUE THREAD

**Issue by steveraysteveray** [BrickSchema/Brick#472]
This rule takes all triples involving a property and duplicates those triples for its super-property. I'm pretty uncomfortable with this, because, for example, it results in:

```
?s skos:exactMatch ?o                 yielding the following assertions:

?s skos:closeMatch ?o
?s skos:mappingRelation ?o
?s skos:semanticRelation ?o
```
...because skos:exactMatch is an rdfs:subProperty of those other properties.

Here's another:
```
?s skos:altLabel ?o                   results in:
?s rdfs:label ?o
```

I recognize that 
"A property p is a subproperty of property q exactly when:
        p(x,y) implies q(x,y)"

...so the rule isn't incorrect, but I'm bothered by explicitly asserting these new triples. 

Thoughts?

**Comment by gtfierro** [comment]
I wanted to hold off on commenting until I had done a couple tests. The immediate consequence of removing the `bsh:RDFSSubPropertyOfRule` is essentially that certain Entity Properties (e.g., `area` vs `grossArea`) won't be properly added. It may be worth specializing the rule to only target those entity properties rather than arbitrary sub-properties. Then, as we add additional uses of `rdfs:subPropertyOf`, we can expand the target of that SHACL rule.
