### ISSUE TITLE
Question about which Brick ontology build to use given a file

### ISSUE THREAD

**Issue by rileywong311** [BrickSchema/Brick#526]
Hi! After looking at the Reference Brick Models on the [BrickSchema website here](https://brickschema.org/resources), the question arose about which ontology version is supposed to be used in accompaniment of them. 

The general question is, is the latest Brick ontology build always backwards compatible with previous versions? If so, how many versions back is this the case? If not the case, would there be a way to find which version of the Brick ontology is needed for a given project?

Specifically, and for example, the Rice Hall `.ttl` appears to be written for Brick 1.0.2 (which there is no available download for) and even has the brick entity `Chilled_Return_Water` which isn't found in any recent versions. How would one use the `Brick.ttl` metadata for this case then?

**Comment by gtfierro** [comment]
Hi @rileywong311 -- generally the models are backwards compatible, but this was really only a focus after Brick 1.2. I would not touch the original 1.0.2/etc models because they are substantially different from modern Brick usage. If you would like some more modern Brick examples I would look [here](https://github.com/gtfierro/mortar-parquet-support/tree/main/mortar-parquet-client/graphs). We should really remove the old reference models from the site....

You can see more docs on Brick versioning here: https://docs.brickschema.org/lifecycle/versioning.html . The Brick "deprecation" mechanism takes care of some of the potential incompatibilities by using SHACL to automatically add the correct types and/or annotations . The `rules.ttl` file in the bricksrc directory of this repository has the SHACL shapes that interpret the deprecation annotations on Brick concepts. So far this has been the primary mechanism for handling transitions w/n the ontology

**Comment by rileywong311** [comment]
Ok great! Thanks!
