### ISSUE TITLE
Air is implicit in Location in common usage

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#53]
E.g., Outside_Temperature_Sensor, Zone_Temperature_Sensor.

Even though it would be explicit if they have "Air" as a tag, people will commonly miss it as Location tags commonly involve Air when they are associated with Points. I would like to investigate if it's possible to have conditional rules. I.e., When Zone && Sensor, Air is inferred.

This is not an urgent issue though.

**Comment by gtfierro** [comment]
@jbkoh  What do you think about removing the `Zone_Temperature_Sensor` class, and introducing `Zone_Air_Temperature_Sensor` as a subclass of `Air_Temperature_Sensor`? We already don't have an `Outside_Temperature_Sensor`

**Comment by jbkoh** [comment]
Sorry that I didn't reply to this one before. Your suggestion is the most straightforward solution but I would like to discuss if there is any other solution here before concluding. The concept of Zone being measured seems prevailing, and people would use it without ``Air`` significantly including the existing systems.

I think there are two cases to solve this ``Zone_Temperature_Sensor`` (a.k.a. ZNT below) problem.
1. We can remove it and just do nothing. We could prevent users from using ZNT with a checker. The tradeoff is usability.
2. We can remove it but provide an inference rule for those externally. E.g., Zone + Temperature + Sensor -> Zone_Air_Temperature_Sensor outside the standard but as a helper function.
3. Include it with ``brick:measures tag:Location``, assuming ``Location`` involves ``Air``. The risk is its actual substance is implicit in the definition of ``Location``.

I understand 1. would be the most unambiguous. But what would be the risk of 3.?

**Comment by gtfierro** [comment]
"Zone" temperature makes it sound like the whole zone's temperature is being measured, which isn't necessarily true. I think Zone Temperature Sensor colloquially refers to a temperature sensor in a room, and not a supply/discharge air temperature sensor.

I like removing it the best, but if we provide a Zone+Temperature+Sensor tag mapping, then we might as well include "Air" there. Future tooling can suggest additional tags that take your given tag set and turn it into one that Brick recognizes.

If we include a `brick:measures tag:Zone` or `tag:Room`, that might be interesting, but we already have a relationship for location. Might be more straightforward to use `brick:hasLocation ?x . ?x rdf:type brick:Location` as a restriction rather than `brick:Measures`. 

I still think removing the class is the best approach for now

**Comment by jbkoh** [comment]
Let's conclude this one with the first solution (removing location+quantity+point.) I will open this issue until we update the implementation.

**Comment by gtfierro** [comment]
Tracking the implementation of the fix in https://github.com/BrickSchema/Brick/pull/75. @jbkoh do you recall other classes that exhibited this issue? `Outside_Temperature_Sensor` doesn't exist.

**Comment by jbkoh** [comment]
``Building_Static_Pressure_Sensor`` is in my mind for now. It should be ``Building_Air_Static_Pressure_Setpoint``. We'd need a more thorough look. I can take a look later today.

**Comment by gtfierro** [comment]
Do you mean `Building_Air_Static_Pressure_Sensor`, rather than `_Setpoint`? I'll do a quick look for location-words in the sensor impl and push some fixes

**Comment by gtfierro** [comment]
I've updated the building/zone/room related classes I found in the sensor, status and setpoint definition files
