### ISSUE TITLE
Import .ttl file to large language model

### ISSUE THREAD

**Issue by s0301132** [BrickSchema/Brick#591]
Hi @gtfierro, I'm trying to let large language model (LLM) understand the ontology using llamaindex and RDF loader so user can query/ explore the Brick model using natural language:

Google Colab example:
[https://colab.research.google.com/drive/16Ygf2IyGNkb725ZqtRmFQjwWBuzFX_kl?usp=sharing](url)

RDF loader:
[https://llamahub.ai/l/file-rdf](url)

However I encounter some issue when I import the `Brick.ttl` and building ontology, the RDF loader only accept n-triples (.nt) format, so I need to convert it to nt format, if the file contain array like relationship such as:
```
bldg:floor_1 a brick:Floor ;
    brick:area [ brick:hasUnit unit:M2 ;
            brick:value 1e+03 ] ;
    brick:hasPart bldg:room_1 .
```
After the conversion using `g.serialize`, the object will become a unreadable string like:

`<http://www.example.com/tlvl#TLVL-RF-CHWP-01.AUTO> <https://brickschema.org/schema/Brick#timeseries> _:nf16794e190c744ccb6be0cd71650e015b58 .`

Is it possible to retain the array information after the conversion? Thanks.

**Comment by gtfierro** [comment]
Hi @s0301132 -- cool project! What you are looking at there is a _blank node_, not an array (see [this page](https://rdflib.readthedocs.io/en/stable/rdf_terms.html) for some explanation, or the note [here](https://docs.brickschema.org/metadata/entity-properties.html#area-of-a-room) for an example). You might want to look at the Concise Bounded Description of a node in order to define subgraphs of related nodes/edges. 

I've done some experiments with LLMs and Brick before and if you are looking to do RAG then you should really consider how to carefully partition the model up

**Comment by s0301132** [comment]
Hi @gtfierro , thanks for the reply, I'm trying to import the building ontology to NebulaGraph with llm query and hoplly have a great result, closing this issue now.

**Comment by gtfierro** [comment]
Keep me updated! I'm curious how it works out
